<?php
/**
 * @file
 *
 * Different custom configs for Cinema Search site.
 */

/**
 * Implements hook_menu().
 */
function custom_menu() {
  return [
    'search/%node/%ctools_js' => [
      'page callback' => 'custom_film_popup',
      'page arguments' => [1, 2],
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function custom_theme($existing, $type, $theme, $path) {
  $templates = drupal_get_path('theme', 'movies') . '/templates';

  return [
    'trailer' => [
      'variables' => [
        'hash' => NULL,
      ],
      'path' => $templates,
      'template' => 'trailer',
    ],
  ];
}

/**
 * Provides form with buttons for search and get random movie.
 */
function custom_action_buttons_form($form, &$form_state) {
  $form['action_buttons'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['action-buttons'],
    ],
  ];
  // Filters button.
  $form['action_buttons']['search_button'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => [
        'action-button',
        'filters-collapsed-button',
        'icon',
        'icon-search',
      ],
    ],
  ];
  // Get random movie button.
  $form['action_buttons']['random_button'] = [
    '#type' => 'button',
    '#name' => 'get_random',
    '#ajax' => [
      'callback' => 'custom_get_random_film_ajax_callback',
      'wrapper' => 'films-outer-wrapper',
      'progress' => FALSE,
    ],
    '#attributes' => [
      'class' => [
        'action-button',
        'get-random-button',
        'icon',
        'icon-dice',
      ],
    ],
  ];
  // Reset button.
  $form['action_buttons']['reset_button'] = [
    '#type' => 'submit',
    '#attributes' => [
      'class' => [
        'action-button',
        'reset-button',
        'icon',
        'icon-reload',
      ],
    ],
  ];

  return $form;
}

/**
 * Replace view content by random node.
 */
function custom_get_random_film_ajax_callback() {
  global $language;

  $query = db_select('node', 'n')
    ->fields('n', ['nid'])
    ->condition('language', $language->language)
    ->orderRandom()
    ->execute()
    ->fetchObject();

  $node = node_load($query->nid);

  $render = node_view($node, 'teaser');

  $commands = [];
  $commands[] = ajax_command_html('#films-outer-wrapper', drupal_render($render));
  $commands[] = ajax_command_css('.filters-collapsed-button', ['display' => 'none']);

  return ['#type' => 'ajax', '#commands' => $commands];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function custom_form_views_exposed_form_alter(&$form, &$form_state) {
  // Set placeholders to exposed search block.
  $form['title']['#attributes'] = ['placeholder' => t('Title')];
  $form['field_year_single']['#attributes'] = ['placeholder' => t('Single year')];
  $form['field_year_range']['min']['#attributes'] = ['placeholder' => t('Min year')];
  $form['field_year_range']['max']['#attributes'] = ['placeholder' => t('Max year')];

  // Multilingual select lists.
  $select_list_fields = [
    'field_genre_tid',
    'field_director_tid',
    'field_actors_tid',
  ];
  foreach ($select_list_fields as $field_name) {
    // Translate select list values.
    foreach ($form[$field_name]['#options'] as $key => $value) {
      $form[$field_name]['#options'][$key] = t($value);
    }
    // Sort values in select list to accordance with translated strings.
    asort($form[$field_name]['#options']);
  }
}

/**
 * Implements hook_node_view_alter().
 *
 * @throws \Exception
 */
function custom_node_view_alter(&$build) {
  if ($build['#entity_type'] == 'node' && $build['#bundle'] == 'film' && $build['#view_mode'] == 'teaser') {
    if (!isset($build['field_poster_image'])) {
      $build['field_poster_image'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => [
            'field-name-field-poster-image',
          ],
        ],
      ];
      // If movie haven't poster set default image and wrap with link on popup.
      $build['field_poster_image'][] = [
        '#markup' => l(
          theme('image', [
            'path' => drupal_get_path('theme', 'movies') . '/images/nopicture.gif',
          ]),
          'search/' . $build['#node']->nid . '/nojs',
          [
            'attributes' => [
              'class' => [
                'ctools-use-modal',
                'ctools-modal-film-popup-style',
              ],
            ],
            'html' => TRUE,
          ]
        ),
      ];
    }
    else {
      // Set poster as link on popup with movie details.
      $build['field_poster_image'][0]['#path'] = [
        'path' => 'search/' . $build['#node']->nid . '/nojs',
        'options' => [
          'attributes' => [
            'class' => [
              'ctools-use-modal',
              'ctools-modal-film-popup-style',
            ],
          ],
        ],
      ];
    }
  }
}

/**
 * Popup's content.
 *
 * @param $node
 *  Node.
 * @param $js
 *  Ctools parameter for check is javascript enabled on browser.
 *
 * @return array
 * @throws \Exception
 */
function custom_film_popup($node, $js) {
  $popup_content = _get_movie_details_and_trailer($node);

  if (!$js) {
    return $popup_content;
  }

  ctools_include('modal');
  ctools_include('ajax');

  $output = [];
  $output[] = ctools_modal_command_display('', $popup_content);

  print ajax_render($output);
  drupal_exit();
}

/**
 * Popup's settings function.
 */
function custom_film_popup_style() {
  static $added = FALSE;
  if ($added == FALSE) {
    $added = TRUE;

    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();

    $popup_style = [
      'film-popup-style' => [
        'modalSize' => [
          'type' => 'fixed',
          'width' => 900,
          'height' => 'auto',
        ],
        'modalOptions' => [
          'opacity' => (float) 0.8,
          'background-color' => '#17222b',
        ],
        'animation' => 'fadeIn',
        'modalTheme' => 'filmTheme',
        'animationSpeed' => 'slow',
      ],
    ];

    drupal_add_js($popup_style, 'setting');
    ctools_add_js('film_popup_style', 'custom');
  }
}

/**
 * Helper function builds node view "popup" with trailer.
 *
 * @param $node
 *  Loaded node.
 *
 * @return array
 */
function _get_movie_details_and_trailer($node) {
  // Add movie's details.
  $node_details_and_trailer = [];
  $node_details_and_trailer[] = node_view($node, 'popup');
  // Add trailer.
  $trailer = !empty($node->field_trailer) ? $node->field_trailer[LANGUAGE_NONE][0]['value'] : FALSE;

  if ($trailer) {
    try {
      $node_details_and_trailer[] = [
        '#markup' => theme('trailer', ['hash' => $trailer]),
      ];
    } catch (Exception $_) {
    }
  }

  return $node_details_and_trailer;
}

/**
 * Implements hook_entity_info_alter().
 */
function custom_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['popup'] = [
    'label' => t('Popup'),
    'custom settings' => TRUE,
  ];
}
